import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import "./globals.css";
import MobileHeader from "@/components/Headers/MobileHeader";
import Headers from "@/components/Headers/Headers";
import Footer from "@/components/Footer/Footer";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <div className="hidden md:block">
          <Headers />
        </div>
        <div className="lg:hidden block">
          <MobileHeader />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
